<?php
/**
 * The template for displaying search results pages
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/#search-result
 *
 * @package eveal
 */

get_header();
?>
 <?php
/**
 * Load More HTML Template for admin_a9a4e8088_t0bk5i
 * Generated by CraftKit Plugin
 */
$query_args = array(
    'post_type' => 'property',
    'posts_per_page' => 6,
    'orderby' => 'date',
    'order' => 'DESC',
    'post_status' => 'publish'
);

$query = new WP_Query($query_args);
$nonce = wp_create_nonce('load_more_admin_a9a4e8088_t0bk5i_nonce');
?>

<div class="admin_a9a4e8088_t0bk5i-container" data-instance="admin_a9a4e8088_t0bk5i">
    <div class="admin_a9a4e8088_t0bk5i-posts">
        <?php if ($query->have_posts()) : while ($query->have_posts()) : $query->the_post(); ?>
            <article class="admin_a9a4e8088_t0bk5i-post-item" data-post-id="<?php echo get_the_ID(); ?>">
                <div class="admin_a9a4e8088_t0bk5i-post-content">
                    <?php if (has_post_thumbnail()) : ?>
                        <div class="admin_a9a4e8088_t0bk5i-post-thumbnail">
                            <a href="<?php echo esc_url(get_permalink()); ?>">
                                <?php the_post_thumbnail('medium'); ?>
                            </a>
                        </div>
                    <?php endif; ?>

                    <div class="admin_a9a4e8088_t0bk5i-post-details">
                        <h3 class="admin_a9a4e8088_t0bk5i-post-title">
                            <a href="<?php echo esc_url(get_permalink()); ?>">
                                <?php echo esc_html(get_the_title()); ?>
                            </a>
                        </h3>

                        <div class="admin_a9a4e8088_t0bk5i-post-meta">
                            <span class="admin_a9a4e8088_t0bk5i-post-date"><?php echo get_the_date(); ?></span>
                        </div>

                        <div class="admin_a9a4e8088_t0bk5i-post-excerpt">
                            <?php echo wp_trim_words(get_the_excerpt() ?: get_the_content(), 20); ?>
                        </div>
                    </div>
                </div>
            </article>
        <?php endwhile; endif; wp_reset_postdata(); ?>
    </div>

    <?php if ($query->max_num_pages > 1) : ?>
        <div class="admin_a9a4e8088_t0bk5i-load-more-container">
            <button class="admin_a9a4e8088_t0bk5i-load-more-btn" data-page="1" data-max-pages="<?php echo $query->max_num_pages; ?>">
                <?php echo esc_html('Load More'); ?>
            </button>
        </div>
    <?php endif; ?>
</div>

<script>jQuery(document).ready(function($) {
    // Load More functionality for admin_a9a4e8088_t0bk5i
    $('.admin_a9a4e8088_t0bk5i-load-more-btn').on('click', function() {
        var $btn = $(this);
        var $container = $('.admin_a9a4e8088_t0bk5i-posts');
        var page = parseInt($btn.data('page')) + 1;
        var maxPages = parseInt($btn.data('max-pages'));

        $btn.prop('disabled', true).text('Loading...');

        $.ajax({
            url: 'http://localhost/eveal/wp-admin/admin-ajax.php',
            type: 'POST',
            data: {
                action: 'load_more_admin_a9a4e8088_t0bk5i',
                page: page,
                nonce: '5c872f3478'
            },
            success: function(response) {
                if (response.success) {
                    $container.append(response.data.html);
                    $btn.data('page', page);

                    if (!response.data.has_more) {
                        $btn.text('No more posts').prop('disabled', true);
                    } else {
                        $btn.prop('disabled', false).text('Load More');
                    }
                }
            },
            error: function() {
                $btn.prop('disabled', false).text('Load More');
            }
        });
    });
});
</script>


<?php
// get_sidebar();
get_footer();
