<?php
/**
 * underscore.js template for the dialog for inserting a post reference field: wizard, step two.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-toolset-shortcode-attribute-info-RFGSecond">
<div class="toolset-shortcodes__tabs_single">
	<h2><?php _e( 'Displaying repeating fields groups (2 of 3)', 'wpcf' ); ?></h2>
	<p style="text-align:center">
		<?php _e( 'Include a filter by post relationship to display groups that belong to the current post in the frontend.', 'wpcf' ); ?>
		<img
			src="<?php echo TYPES_RELPATH . '/public/img/repeating-fields-group-wizard/step2.png'; ?>"
			alt="<?php echo esc_attr( __( 'Step 2', 'wpcf' ) ); ?>"
			style="display:block;margin:10px auto 0;border:solid 2px #ccc;box-shadow:0 10px 20px -15px;max-width:80%;"
		/>
	</p>
</div>
</script>
