<?php
/**
 * underscore.js template for the dialog for inserting a post reference field: wizard, step two.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-toolset-shortcode-attribute-info-postReferenceFieldWizardSecond">
<div class="toolset-shortcodes__tabs_single">
	<h2><?php _e( 'Displaying post reference fields (2 of 3)', 'wpcf' ); ?></h2>
	<p style="text-align:center">
		<?php _e( 'Click on the <strong>Post Selection</strong> tab and select "A post related to the current post, set by a Types post reference field".', 'wpcf' ); ?>
		<img
			src="<?php echo TYPES_RELPATH . '/public/img/post-reference-field-wizard/step2.png'; ?>"
			alt="<?php echo esc_attr( __( 'Step 2', 'wpcf' ) ); ?>"
			style="display:block;margin:10px auto 0;border:solid 2px #ccc;box-shadow:0 10px 20px -15px;max-width:80%;"
		/>
	</p>
</div>
</script>
