<?php
/**
 * underscore.js template for the dialog for inserting a post reference field: wizard, step one.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-toolset-shortcode-attribute-info-postReferenceFieldWizardFirst">
<div class="toolset-shortcodes__tabs_single">
	<h2><?php _e( 'Displaying post reference fields (1 of 3)', 'wpcf' ); ?></h2>
	<p style="text-align:center">
		<?php _e( 'Select any field that you wish to insert (like Title, URL, etc). This includes custom fields for the referenced post.', 'wpcf' ); ?>
		<img
			src="<?php echo TYPES_RELPATH . '/public/img/post-reference-field-wizard/step1.png'; ?>"
			alt="<?php echo esc_attr( __( 'Step 1', 'wpcf' ) ); ?>"
			style="display:block;margin:10px auto 0;border:solid 2px #ccc;box-shadow:0 10px 20px -15px;max-width:80%;"
		/>
	</p>
</div>
</script>
